### ISSUE TITLE
Two questions about HELLOIMGUI_USE_SDL_DIRECTX11 and ImGuiConfigFlags_ViewportsEnable

### ISSUE THREAD

**Issue by MichaelKv** [pthom/hello_imgui#15] opened 2021-04-27 00:00 UTC
Hello. I have two questions.
1. What is HELLOIMGUI_USE_SDL_DIRECTX11 for? It does build but there is no such a backend so FactorRunner emits an exception.
2. I have uncommented io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; line in void SetupDefaultImGuiConfig() and the hello_world.exe application window content gets stuck to the upper left corner of the primary monitor (I have two monitors). I can move the application window and resize it. The content resizes but does not move. May it be fixed?
The hello_imgui_demodocking.exe is kind of works but the behavior of the fps line is strange (it is stuck to a constant position too). hello_imgui_demo_minimal.exe behaves the same way as described in (2). hello_imgui_demo_classic.exe work normally (at least I have not noticed an unusual behavior).

**Comment by pthom** [comment] 2021-04-27 11:24
Hi,

Thanks for the detailed description. 

1. I have removed HELLOIMGUI_USE_SDL_DIRECTX11 : it was here, but not implemented; sorry for that. (I welcome pull requests that had interesting features although ;-)

2. I have fixed the issue with ImGuiConfigFlags_ViewportsEnable: see https://github.com/pthom/hello_imgui/commit/53e9262d22e02346dee2dafd677d620c7b84dd3b
The demo hello_imgui_demodocking will show it working. 

Remark: you do not need to modify SetupDefaultImGuiConfig() in hello_imgui in order to activate it; you can simply write this somewhere in your initialization:

````cpp
    HelloImGui::RunnerParams runnerParams;
 
    ...

    runnerParams.callbacks.SetupImGuiConfig = [] {
        ImGuiIO& io = ImGui::GetIO();
        io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
#ifndef __EMSCRIPTEN__
        io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
#endif
    };
````

Please tell me if the issue is fixed on your side :-)

**Comment by MichaelKv** [comment] 2021-04-28 22:22
It works now. Thank you.
But why do you use exception in FactorRunner if there is no backend? I do not think an application can work in this case at all so it would be more logical to emit an error in this case during the compilation.

**Comment by pthom** [comment] 2021-04-29 10:53
See c463e934f8764e75cb047ac5f594d40e13459022 , I added a check for that.

I close this issue, since everything should be ok now

**Closed by pthom** 2021-04-29 10:53 UTC
